export const FINISHED_ORDER_STATUSES = {
  orderStatus: ['6', '2'] as string[], // 6 = Entregue, 2 = Cancelada
  carrierStatus: [
    // Status de Entrega
    'ENTREGA REALIZADA',
    'ENTREGA REALIZADA - (ARQ. POD)',
    'ENTREGUE',
    'OBJETO ENTREGUE AO DESTINATÁRIO',
    'OBJETO ENTREGUE NA CAIXA DE CORREIOS INTELIGENTE',
    
    // Status de Devolução
    'OBJETO ENTREGUE AO REMETENTE',
    'DEVOLVIDA AO REMETENTE',
    'OBJETO DEVOLVIDO AOS CORREIOS',
    'OBJETO SERÁ DEVOLVIDO POR SOLICITAÇÃO DO CONTRATANTE/REMETENTE',
    'DEVOLUÇÃO EM ANDAMENTO PARA O REMETENTE',
    'EMBARQUE DE DEVOLUÇÃO RECEBIDO',
    'EMBARQUE DE DEVOLUÇÃO RECEBIDO TRANSBORDO',
    'AGUARDANDO FREQUÊNCIA DE DEVOLUÇÃO'
  ].map(status => status.toUpperCase())
} as const;

export const CARRIER_STATUS_GROUPS = {
  ENTREGA_REALIZADA: [
    'ENTREGA REALIZADA',
    'ENTREGA REALIZADA - (ARQ. POD)',
    'ENTREGUE',
    'OBJETO ENTREGUE AO DESTINATÁRIO',
    'OBJETO ENTREGUE NA CAIXA DE CORREIOS INTELIGENTE'
  ],
  DEVOLUCAO: [
    'OBJETO ENTREGUE AO REMETENTE',
    'DEVOLVIDA AO REMETENTE',
    'OBJETO DEVOLVIDO AOS CORREIOS',
    'OBJETO SERÁ DEVOLVIDO POR SOLICITAÇÃO DO CONTRATANTE/REMETENTE',
    'DEVOLUÇÃO EM ANDAMENTO PARA O REMETENTE',
    'EMBARQUE DE DEVOLUÇÃO RECEBIDO',
    'EMBARQUE DE DEVOLUÇÃO RECEBIDO TRANSBORDO',
    'AGUARDANDO FREQUÊNCIA DE DEVOLUÇÃO'
  ],
  EM_TRANSITO: [
    'AGUARDANDO CUBAGEM',
    'ARQUIVO RECEBIDO',
    'BIPE DE PACOTE PROBLEMÁTICO',
    'CANCELADO PELO DESTINATARIO',
    'COLETA RECEBIDA NO CD',
    'EM ROTA',
    'EM TRANSFERÊNCIA SECUNDÁRIA',
    'ENTREGA PROGRAMADA',
    'PROCESSO DE ENTREGA',
    'RECEBIDO CD',
    'RECEBIDO/TRANSFERÊNCIA SECUNDÁRIA',
    'RETIRADO',
    'RETIRADO DA CAF ANTERIOR',
    'SAÍDA PARA ENTREGA CANCELADA',
    'TRANSBORDO EM',
    'TRANSFERENCIA PARA',
    'OBJETO AINDA NÃO CHEGOU À UNIDADE',
    'OBJETO ENCAMINHADO'
  ],
  DISPONIVEL_RETIRADA: [
    'DISPONÍVEL PARA RETIRADA',
    'OBJETO AGUARDANDO RETIRADA NO ENDEREÇO INDICADO',
    'OBJETO DISPONÍVEL PARA RETIRADA EM CAIXA POSTAL'
  ],
  OCORRENCIA_ENTREGA: [
    'A ENTREGA NÃO PODE SER EFETUADA - CARTEIRO NÃO ATENDIDO',
    'ASSINATURA DE ENCOMENDA',
    'CLIENTE AUSENTE/ESTABELECIMENTO FECHADO',
    'DESTINATARIO MUDOU-SE',
    'DUAS OU MAIS VEZES AUSENTE/FECHADO',
    'EM ANÁLISE DA PREVENÇÃO',
    'EMBALAGEM EM ANALISE',
    'ENTREGA NÃO PODE SER EFETUADA',
    'OBJETO ENCAMINHADO PARA RETIRADA NO ENDEREÇO INDICADO',
    'OBJETO NÃO ENTREGUE - ENDEREÇO INEXISTENTE',
    'OBJETO NÃO ENTREGUE - PRAZO DE RETIRADA ENCERRADO',
    'TENTATIVA DE ENTREGA NÃO EFETUADA'
  ]
} as const;

// Função auxiliar para verificar se um status indica finalização
export function isFinishedStatus(status: string, type: 'order' | 'carrier'): boolean {
  const statusList = type === 'order' 
    ? FINISHED_ORDER_STATUSES.orderStatus 
    : FINISHED_ORDER_STATUSES.carrierStatus;
  
  return statusList.includes(status) || statusList.includes(status.toUpperCase());
} 